stages:
  - build
  - pages

# 1. Build stage: compile and package your JAR
build:
  stage: build
  image: maven:3.8.8-openjdk-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/halma.jar
    expire_in: 1 week

# 2. Pages stage: expose halma.jar + Javadoc via GitLab Pages
pages:
  stage: pages
  image: maven:3.8.8-openjdk-21
  dependencies:
    - build
  script:
    # 2.1 generate Javadoc
    - mvn javadoc:javadoc -q
    # 2.2 prepare public/
    - mkdir public
    - cp target/halma.jar public/
    - cp -r target/site/apidocs public/
  artifacts:
    paths:
      - public
  only:
    - main