stages:
  - build
  - pages

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/halma.jar

pages:
  stage: pages
  dependencies:
    - build
  script:
    - mkdir public
    - cp target/halma.jar public/
    - mvn javadoc:aggregate
    - cp -r target/site/apidocs public/
  artifacts:
    paths:
      - public
  only:
    - main